public enum CustomerSpeechType
{
	THIS_IS_THEFT = 0,
	EXPENSIVE = 1,
	EXPENSIVE_FOR_ME = 2,
	CANT_FIND_ANYTHING = 3,
	CANT_FIND_SOMETHING = 4,
	CHANGE_PRICE_WHILE_SHOPPING = 5,
	FULL_CHECKOUTS = 6,
	FULL_RACKS = 7
}
